Proper rounding implementation
flyx/DSA-Heldendokument pull request #23
Opened 2024-03-14 21:31 UTC by davidfoerster

…in accordance with Basisregelwerk page 13 (“Rundungen”).

The previous implementation relies on `string.format("%.0f", x)` whose behaviour is inconsistent across Lua versions.

Potential caveat: this implementation rounds halfway cases away from zero while the rules require that (barring special cases) they should be rounded “up”, i. e. towards positive infinity. However, I have yet to see a rule that requires the rounding of *negative* values (to any other value than zero); instances where negative modifiers need rounding (e. g. encumbrance), the rounding is supposed to be applied to their absolute values, i. e. away from zero.

2024-03-17 09:03 UTC, flyx requested changes
Generell okay, da war schon viel Wildwuchs in den Rundungsmechanismen. 

Allerdings zieht ungerade eBE jetzt einen Punkt zu viel von der AT ab, das müsstest du noch fixen.

2024-03-17 09:03 UTC, flyx commented on src/kampfbogen.lua
> +    tex.sprint(-2, atpa_mod(atb - math.round(ebe/2, true), talent.AT, v["TP/KK Schwelle"], v["TP/KK Schritt"], 0))
Selbe Geschichte wie oben.

2024-03-17 13:10 UTC, davidfoerster commented
Danke für die Kommentare! Ich kümmere mich im Verlauf der Woche um die beiden Probleme.

2024-03-21 00:47 UTC, davidfoerster commented
@flyx Bitteschön.

2024-03-23 14:18 UTC, merged